// src/components/LabWorkspace.styles.js

export const styles = {
  container: {
    display: "flex",
    flexDirection: "row",
    height: "100vh",
    backgroundColor: "#0d1117",
    color: "#c9d1d9",
    fontFamily: "Segoe UI, Tahoma, Geneva, Verdana, sans-serif",
  },
  taskPanel: {
    flex: "0 0 400px",
    padding: "40px",
    borderRight: "1px solid #30363d",
    backgroundColor: "#0d1117",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    overflowY: "auto",
    textAlign: "left",
  },
  terminalPanel: {
    flex: 1,
    backgroundColor: "#000000",
    position: "relative",
    padding: "10px",
  },
  header: {
    borderBottom: "1px solid #30363d",
    paddingBottom: "15px",
    marginBottom: "10px",
  },
  badge: {
    backgroundColor: "#238636",
    color: "white",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "bold",
    display: "inline-block",
    marginTop: "10px",
  },
  description: {
    fontSize: "16px",
    lineHeight: "1.5",
  },
  taskBox: {
    backgroundColor: "#161b22",
    padding: "25px",
    borderRadius: "8px",
    border: "1px solid #30363d",
    marginTop: "20px",
  },
  input: {
    width: "90%",
    padding: "12px",
    marginTop: "15px",
    backgroundColor: "#0d1117",
    border: "1px solid #30363d",
    color: "#c9d1d9",
    borderRadius: "6px",
    fontSize: "16px",
  },
  button: {
    marginTop: "15px",
    padding: "12px 24px",
    backgroundColor: "#238636",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "16px",
    display: "block",
  },
  terminateBtn: {
    backgroundColor: "transparent",
    color: "#f85149",
    border: "1px solid #f85149",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "14px",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    gap: "5px",
  },
};